# api/v1/auth/signup POST
# api/v1/auth/login POST
# api/v1/cow POST
# api/v1/cow/1 GET
# api/v1/cow GET
# api/v1/cow PUT
# api/v1/cow DELETE
# api/v1/cow/milk DELETE
# api/v1/cow/milk POST
# api/v1/cow/milk GET
# api/v1/cow/milk PUT
