"""empty message

Revision ID: 505bf2007735
Revises: d99a8f876237
Create Date: 2018-10-11 09:46:04.347829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505bf2007735'
down_revision = 'd99a8f876237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'revoked_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revoked_tokens', type_='foreignkey')
    op.drop_column('revoked_tokens', 'user_id')
    # ### end Alembic commands ###
