"""empty message

Revision ID: 73a2f03ee75f
Revises: 35c0c822ad4e
Create Date: 2018-09-24 23:37:12.589992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a2f03ee75f'
down_revision = '35c0c822ad4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=255), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milk')
    # ### end Alembic commands ###
