"""empty message

Revision ID: 802e1b98f662
Revises: 6588035e193c
Create Date: 2018-10-04 18:06:21.033416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802e1b98f662'
down_revision = '6588035e193c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moo_name', sa.String(length=255), nullable=True),
    sa.Column('breed', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('cow_health', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cow.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milk')
    op.drop_table('cow')
    # ### end Alembic commands ###
