"""empty message

Revision ID: b56257f2fd6f
Revises: 906d5e2ac313
Create Date: 2018-10-23 08:56:09.237829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56257f2fd6f'
down_revision = '906d5e2ac313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milk', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milk', 'total')
    # ### end Alembic commands ###
