"""empty message

Revision ID: fa9b56c9fca2
Revises: 73a2f03ee75f
Create Date: 2018-09-24 23:43:23.240974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9b56c9fca2'
down_revision = '73a2f03ee75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=255), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milk')
    # ### end Alembic commands ###
